// Generated by scripts/generate-tokens.py from Design/tokens.json. Do not edit by hand.
import AppKit
import SwiftUI

/// Semantic colours for AppKit. Each resolves to its light or dark value from the drawing appearance.
enum NSPalette {
    static let surfacePage = NSColor.verb(light: 0xF9F4EB, 1.00, dark: 0x191512, 1.00)
    static let surfaceRaised = NSColor.verb(light: 0xFDFAF4, 1.00, dark: 0x221E1A, 1.00)
    static let surfaceSunken = NSColor.verb(light: 0xF0EAE0, 1.00, dark: 0x120F0D, 1.00)
    static let surfaceSelected = NSColor.verb(light: 0xFDFAF4, 1.00, dark: 0x3A342F, 1.00)
    static let surfaceInverse = NSColor.verb(light: 0x27221D, 1.00, dark: 0xEEE9DF, 1.00)
    static let surfaceInverseHover = NSColor.verb(light: 0x3A342F, 1.00, dark: 0xDCD7CD, 1.00)
    static let textPrimary = NSColor.verb(light: 0x27221D, 1.00, dark: 0xEEE9DF, 1.00)
    static let textSecondary = NSColor.verb(light: 0x615B55, 1.00, dark: 0xB7B2AA, 1.00)
    static let textTertiary = NSColor.verb(light: 0x756F69, 1.00, dark: 0x9F9B93, 1.00)
    static let textOnInverse = NSColor.verb(light: 0xFDFAF4, 1.00, dark: 0x27221D, 1.00)
    static let accent = NSColor.verb(light: 0xB43B27, 1.00, dark: 0xEA856A, 1.00)
    static let accentStrong = NSColor.verb(light: 0x9C2C20, 1.00, dark: 0xF49F81, 1.00)
    static let accentTint = NSColor.verb(light: 0xB43B27, 0.09, dark: 0xEA856A, 0.14)
    static let borderSubtle = NSColor.verb(light: 0x27221D, 0.10, dark: 0xEEE9DF, 0.12)
    static let borderStrong = NSColor.verb(light: 0x857F78, 1.00, dark: 0x79736D, 1.00)
    static let controlOn = NSColor.verb(light: 0x27221D, 1.00, dark: 0xEEE9DF, 1.00)
    static let controlKnob = NSColor.verb(light: 0xFDFAF4, 1.00, dark: 0xDCD7CD, 1.00)
    static let controlKnobOn = NSColor.verb(light: 0xFDFAF4, 1.00, dark: 0x191512, 1.00)
    static let fillHover = NSColor.verb(light: 0x27221D, 0.05, dark: 0xEEE9DF, 0.06)
    static let fillPressed = NSColor.verb(light: 0x27221D, 0.09, dark: 0xEEE9DF, 0.10)
    static let success = NSColor.verb(light: 0x436737, 1.00, dark: 0x95BF87, 1.00)
    static let warning = NSColor.verb(light: 0x8E5D1E, 1.00, dark: 0xE3B56D, 1.00)
    static let warningTint = NSColor.verb(light: 0x8E5D1E, 0.12, dark: 0xE3B56D, 0.14)
    static let danger = NSColor.verb(light: 0x972540, 1.00, dark: 0xEB869A, 1.00)
    static let shadow = NSColor.verb(light: 0x2A1F14, 0.28, dark: 0x000000, 0.50)
}

/// Semantic colours for SwiftUI.
enum Palette {
    static let surfacePage = Color(nsColor: NSPalette.surfacePage)
    static let surfaceRaised = Color(nsColor: NSPalette.surfaceRaised)
    static let surfaceSunken = Color(nsColor: NSPalette.surfaceSunken)
    static let surfaceSelected = Color(nsColor: NSPalette.surfaceSelected)
    static let surfaceInverse = Color(nsColor: NSPalette.surfaceInverse)
    static let surfaceInverseHover = Color(nsColor: NSPalette.surfaceInverseHover)
    static let textPrimary = Color(nsColor: NSPalette.textPrimary)
    static let textSecondary = Color(nsColor: NSPalette.textSecondary)
    static let textTertiary = Color(nsColor: NSPalette.textTertiary)
    static let textOnInverse = Color(nsColor: NSPalette.textOnInverse)
    static let accent = Color(nsColor: NSPalette.accent)
    static let accentStrong = Color(nsColor: NSPalette.accentStrong)
    static let accentTint = Color(nsColor: NSPalette.accentTint)
    static let borderSubtle = Color(nsColor: NSPalette.borderSubtle)
    static let borderStrong = Color(nsColor: NSPalette.borderStrong)
    static let controlOn = Color(nsColor: NSPalette.controlOn)
    static let controlKnob = Color(nsColor: NSPalette.controlKnob)
    static let controlKnobOn = Color(nsColor: NSPalette.controlKnobOn)
    static let fillHover = Color(nsColor: NSPalette.fillHover)
    static let fillPressed = Color(nsColor: NSPalette.fillPressed)
    static let success = Color(nsColor: NSPalette.success)
    static let warning = Color(nsColor: NSPalette.warning)
    static let warningTint = Color(nsColor: NSPalette.warningTint)
    static let danger = Color(nsColor: NSPalette.danger)
    static let shadow = Color(nsColor: NSPalette.shadow)
}

/// Type sizes in points. Display sizes use New York, everything else SF Pro.
enum TypeSize {
    static let caption: CGFloat = 11
    static let footnote: CGFloat = 12
    static let body: CGFloat = 13
    static let callout: CGFloat = 15
    static let reading: CGFloat = 17
    static let title3: CGFloat = 20
    static let title2: CGFloat = 26
    static let title1: CGFloat = 34
    static let hero: CGFloat = 44
}

/// Line-height multipliers.
enum Leading {
    static let tight: CGFloat = 1.1
    static let ui: CGFloat = 1.35
    static let reading: CGFloat = 1.5
}

/// Letter spacing in points.
enum Tracking {
    static let display: CGFloat = -0.4
    static let rubric: CGFloat = 0.8
}

/// The 4 pt spacing scale.
enum Space {
    static let xxs: CGFloat = 2
    static let xs: CGFloat = 4
    static let sm: CGFloat = 8
    static let md: CGFloat = 12
    static let base: CGFloat = 16
    static let lg: CGFloat = 20
    static let xl: CGFloat = 24
    static let xxl: CGFloat = 32
    static let xxxl: CGFloat = 40
    static let huge: CGFloat = 56
    static let page: CGFloat = 48
}

/// Corner radii.
enum Radius {
    static let xs: CGFloat = 4
    static let sm: CGFloat = 6
    static let md: CGFloat = 9
    static let lg: CGFloat = 14
    static let xl: CGFloat = 20
}

/// Fixed dimensions.
enum Sizing {
    static let controlMin: CGFloat = 44
    static let optionMin: CGFloat = 48
    static let sidebar: CGFloat = 224
    static let contentMax: CGFloat = 880
    static let overlayWidth: CGFloat = 400
    static let overlayHeight: CGFloat = 60
}

/// Durations in seconds.
enum Motion {
    static let fast: Double = 0.12
    static let base: Double = 0.2
    static let slow: Double = 0.32
    static let linger: Double = 2
    static let lingerFailure: Double = 5
}

extension NSColor {
    static func verb(light: UInt32, _ lightAlpha: CGFloat, dark: UInt32, _ darkAlpha: CGFloat) -> NSColor {
        NSColor(name: nil) { appearance in
            let isDark = appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
            let (value, alpha) = isDark ? (dark, darkAlpha) : (light, lightAlpha)
            return NSColor(srgbRed: CGFloat((value >> 16) & 0xFF) / 255, green: CGFloat((value >> 8) & 0xFF) / 255, blue: CGFloat(value & 0xFF) / 255, alpha: alpha)
        }
    }
}
