#!/usr/bin/env python3
"""Generate Verb's platform tokens from the one source, Design/tokens.json.

Writes Sources/Verb/DesignTokens.swift and Design/tokens.css, then prints a
WCAG 2.2 contrast report for the required pairs in light and dark. Exits 1 if
any required pair fails, so a palette edit cannot silently break legibility.

    python3 scripts/generate-tokens.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "Design" / "tokens.json"
SWIFT = ROOT / "Sources" / "Verb" / "DesignTokens.swift"
CSS = ROOT / "Design" / "tokens.css"

# (foreground, background, minimum). Alpha tokens are composited over the page first.
REQUIRED = [
    ("text-primary", "surface-page", 4.5), ("text-primary", "surface-raised", 4.5), ("text-primary", "surface-sunken", 4.5), ("text-primary", "surface-selected", 4.5),
    ("text-secondary", "surface-page", 4.5), ("text-secondary", "surface-raised", 4.5), ("text-secondary", "surface-sunken", 4.5),
    ("text-tertiary", "surface-page", 4.5), ("text-tertiary", "surface-raised", 4.5),
    ("accent", "surface-page", 4.5), ("accent", "surface-raised", 4.5), ("accent", "surface-sunken", 4.5),
    ("accent", "accent-tint", 4.5), ("text-primary", "accent-tint", 4.5),
    ("text-on-inverse", "surface-inverse", 4.5), ("text-on-inverse", "surface-inverse-hover", 4.5),
    ("danger", "surface-page", 4.5), ("danger", "surface-raised", 4.5),
    ("success", "surface-page", 4.5), ("success", "surface-raised", 4.5),
    ("warning", "surface-page", 4.5), ("warning", "surface-raised", 4.5), ("text-primary", "warning-tint", 4.5),
    ("border-strong", "surface-page", 3.0), ("border-strong", "surface-raised", 3.0),
    ("accent", "surface-raised", 3.0),  # the live recording dot as a graphic
    ("control-on", "surface-page", 3.0), ("control-on", "surface-raised", 3.0), ("control-knob-on", "control-on", 3.0),
]


def camel(name):
    head, *rest = re.split(r"[-.]", name)
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def resolve(value, tokens, depth=0):
    match = re.fullmatch(r"\{([^}]+)\}", value)
    if not match:
        return value
    if depth > 8:
        raise ValueError(f"alias loop at {value}")
    node = tokens
    for key in match.group(1).split("."):
        node = node[key]
    return resolve(node["$value"], tokens, depth + 1)


def rgba(hex_value):
    h = hex_value.lstrip("#")
    if len(h) not in (6, 8):
        raise ValueError(f"bad colour {hex_value}")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    a = int(h[6:8], 16) / 255 if len(h) == 8 else 1.0
    return r, g, b, a


def over(fg, bg):
    r, g, b, a = rgba(fg)
    R, G, B, _ = rgba(bg)
    mix = lambda top, bottom: round(top * a + bottom * (1 - a))
    return "#%02X%02X%02X" % (mix(r, R), mix(g, G), mix(b, B))


def luminance(hex_value):
    def channel(c):
        c = c / 255
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b, _ = rgba(hex_value)
    return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)


def contrast(fg, bg):
    hi, lo = sorted((luminance(fg), luminance(bg)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def colors(section, tokens):
    return {name: resolve(node["$value"], tokens) for name, node in section.items() if not name.startswith("$")}


def points(value):
    return float(str(value).replace("pt", "").replace("ms", ""))


def fmt(number):
    return ("%g" % number)


def main():
    tokens = json.loads(SOURCE.read_text())
    light = colors(tokens["semantic"]["color"], tokens)
    dark = {**light, **colors(tokens["dark"]["semantic"]["color"], tokens)}
    missing = set(light) - set(tokens["dark"]["semantic"]["color"])
    if missing:
        print("Dark overrides missing for:", ", ".join(sorted(missing)))
        return 1

    # Contrast report, measured on the resolved values.
    failures = 0
    for mode, table in (("light", light), ("dark", dark)):
        print(f"{mode}:")
        page = table["surface-page"]
        flat = lambda name: over(table[name], page) if len(table[name].lstrip("#")) == 8 else table[name]
        for fg, bg, need in REQUIRED:
            background = flat(bg)
            foreground = over(table[fg], background) if len(table[fg].lstrip("#")) == 8 else table[fg]
            ratio = contrast(foreground, background)
            ok = ratio >= need
            failures += not ok
            print(f"  {'PASS' if ok else 'FAIL'}  {fg:22} on {bg:22} {ratio:5.2f}:1  (min {need})")

    # Swift.
    lines = [
        "// Generated by scripts/generate-tokens.py from Design/tokens.json. Do not edit by hand.",
        "import AppKit",
        "import SwiftUI",
        "",
        "/// Semantic colours for AppKit. Each resolves to its light or dark value from the drawing appearance.",
        "enum NSPalette {",
    ]
    for name in light:
        lr, lg, lb, la = rgba(light[name])
        dr, dg, db, da = rgba(dark[name])
        lines.append(
            f"    static let {camel(name)} = NSColor.verb(light: 0x{lr:02X}{lg:02X}{lb:02X}, {la:.2f}, dark: 0x{dr:02X}{dg:02X}{db:02X}, {da:.2f})"
        )
    lines += ["}", "", "/// Semantic colours for SwiftUI.", "enum Palette {"]
    for name in light:
        lines.append(f"    static let {camel(name)} = Color(nsColor: NSPalette.{camel(name)})")
    lines += ["}", ""]

    typography = tokens["typography"]
    lines.append("/// Type sizes in points. Display sizes use New York, everything else SF Pro.")
    lines.append("enum TypeSize {")
    for name, node in typography["size"].items():
        if not name.startswith("$"):
            lines.append(f"    static let {camel(name)}: CGFloat = {fmt(points(node['$value']))}")
    lines += ["}", "", "/// Line-height multipliers.", "enum Leading {"]
    for name, node in typography["leading"].items():
        if not name.startswith("$"):
            lines.append(f"    static let {camel(name)}: CGFloat = {fmt(node['$value'])}")
    lines += ["}", "", "/// Letter spacing in points.", "enum Tracking {"]
    for name, node in typography["tracking"].items():
        if not name.startswith("$"):
            lines.append(f"    static let {camel(name)}: CGFloat = {fmt(points(node['$value']))}")
    lines.append("}")
    for title, key, doc in (("Space", "spacing", "The 4 pt spacing scale."), ("Radius", "radius", "Corner radii."), ("Sizing", "sizing", "Fixed dimensions.")):
        lines += ["", f"/// {doc}", f"enum {title} {{"]
        for name, node in tokens[key].items():
            if not name.startswith("$"):
                lines.append(f"    static let {camel(name)}: CGFloat = {fmt(points(node['$value']))}")
        lines.append("}")
    lines += ["", "/// Durations in seconds.", "enum Motion {"]
    for name, node in tokens["motion"]["duration"].items():
        if not name.startswith("$"):
            lines.append(f"    static let {camel(name)}: Double = {fmt(points(node['$value']) / 1000)}")
    lines += [
        "}",
        "",
        "extension NSColor {",
        "    static func verb(light: UInt32, _ lightAlpha: CGFloat, dark: UInt32, _ darkAlpha: CGFloat) -> NSColor {",
        "        NSColor(name: nil) { appearance in",
        "            let isDark = appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua",
        "            let (value, alpha) = isDark ? (dark, darkAlpha) : (light, lightAlpha)",
        "            return NSColor(srgbRed: CGFloat((value >> 16) & 0xFF) / 255, green: CGFloat((value >> 8) & 0xFF) / 255, blue: CGFloat(value & 0xFF) / 255, alpha: alpha)",
        "        }",
        "    }",
        "}",
        "",
    ]
    SWIFT.parent.mkdir(parents=True, exist_ok=True)
    SWIFT.write_text("\n".join(lines))

    # CSS for the brand guidelines page, with both ways of choosing dark.
    def block(table):
        return "\n".join(f"  --{name}: {value};" for name, value in table.items())
    dark_only = {k: v for k, v in dark.items()}
    sizes = "\n".join(
        f"  --size-{name}: {fmt(points(node['$value']))}px;" for name, node in typography["size"].items() if not name.startswith("$")
    )
    space = "\n".join(f"  --space-{name}: {fmt(points(node['$value']))}px;" for name, node in tokens["spacing"].items() if not name.startswith("$"))
    radius = "\n".join(f"  --radius-{name}: {fmt(points(node['$value']))}px;" for name, node in tokens["radius"].items() if not name.startswith("$"))
    css = (
        "/* Generated by scripts/generate-tokens.py from Design/tokens.json. Do not edit by hand. */\n"
        f":root {{\n{block(light)}\n{sizes}\n{space}\n{radius}\n}}\n"
        f"@media (prefers-color-scheme: dark) {{\n  :root:not([data-theme=\"light\"]) {{\n{block(dark_only).replace(chr(10) + '  ', chr(10) + '    ').replace('  --', '    --', 1)}\n  }}\n}}\n"
        f":root[data-theme=\"dark\"] {{\n{block(dark_only)}\n}}\n"
    )
    CSS.write_text(css)
    print(f"\nWrote {SWIFT.relative_to(ROOT)} and {CSS.relative_to(ROOT)}")
    print("Contrast failures:", failures)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
